module "caf" {
  source = "../"

  global_settings                = var.global_settings
  diagnostics                    = local.remote.diagnostics
  gitlab_projects                = var.gitlab_projects
  current_landingzone_key        = var.landingzone.key
  tenant_id                      = var.tenant_id
  logged_user_objectId           = var.logged_user_objectId
  logged_aad_app_objectId        = var.logged_aad_app_objectId
  resource_groups                = var.resource_groups
  storage_accounts               = var.storage_accounts
  azuread_groups                 = var.azuread_groups
  azuread_apps                   = var.azuread_apps
  azuread_users                  = var.azuread_users
  azuread_roles                  = var.azuread_roles
  tags                           = local.tags
  keyvaults                      = var.keyvaults
  keyvault_access_policies       = var.keyvault_access_policies
  keyvault_certificate_issuers   = var.keyvault_certificate_issuers
  managed_identities             = var.managed_identities
  role_mapping                   = var.role_mapping
  custom_role_definitions        = var.custom_role_definitions
  log_analytics                  = var.log_analytics
  event_hub_namespaces           = var.event_hub_namespaces
  event_hubs                     = var.event_hubs
  event_hub_auth_rules           = var.event_hub_auth_rules
  event_hub_namespace_auth_rules = var.event_hub_namespace_auth_rules
  event_hub_consumer_groups      = var.event_hub_consumer_groups
}
